dashboard:
  container_name: dashboard
  build: .
  volumes:
    - .:/usr/src/app/
  ports:
    - "5000:5000"
  command: "npm run docker:local"
  environment:
    PORT: 5000
    WEBSERVICE_URL: http://192.168.99.100:8080
    BUNYAN_LEVEL: debug
