dashboard:
  container_name: dashboard
  build: .
  volumes:
    - .:/usr/src/app/
  ports:
    - "5000:5000"
  command: "npm run docker:local"
  environment:
    PORT: 5000
    WEBSERVICE_URL: "$WEBSERVICE_URL"
