dashboard:
  container_name: dashboard
  build: .
  volumes:
    - .:/usr/src/app/
  ports:
    - "5000:5000"
  command: "npm run dev:local:docker"
  environment:
    PORT: 5000
    NODE_ENV: development
    WEBSERVICE_URL: "$WEBSERVICE_URL"
    BUNYAN_LEVEL: "debug"
    BUNYAN_FORMAT: "short"
